version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypasswd
    volumes:
      - db:/home/sijoonlee/Documents/RateHub/playground/express-server/postgres_db2
    ports:
      - "5432:5432"

volumes:
  db:
    driver: local